const Map<String, String> appStringsEn = {
  'appName': 'PantryPal',
  'appTagline': 'Smart home food management',
  'splashLoading': 'Loading your pantry...',
  'onboardingTitle1': 'Manage your pantry',
  'onboardingDesc1': 'Add food items, categorize by meat, veggies, drinks... and track everything at home.',
  'onboardingTitle2': 'Expiry reminders',
  'onboardingDesc2': 'Set expiry dates and get notified before food goes bad.',
  'onboardingTitle3': 'Earn stars & customize',
  'onboardingDesc3': 'Earn free stars or buy packs via Google Play to unlock themes, card skins and premium features.',
  'getStarted': 'Get started',
  'skip': 'Skip',
  'next': 'Next',
  'navPantry': 'Pantry',
  'navShopping': 'Shopping',
  'navShop': 'Shop',
  'navSettings': 'Settings',
  'pantryTitle': 'Food Pantry',
  'pantrySubtitle': 'Track expiry dates for all food',
  'pantryEmpty': 'No food yet. Tap + to add!',
  'addFood': 'Add food',
  'editFood': 'Edit food',
  'foodName': 'Food name',
  'category': 'Category',
  'quantity': 'Quantity',
  'unit': 'Unit (g, ml, box...)',
  'hasExpiry': 'Has expiry date',
  'expiryDate': 'Expiry date',
  'notes': 'Notes',
  'noExpiry': 'No expiry',
  'expiredLabel': 'Expired',
  'expiresToday': 'Expires today',
  'daysLeft': '{days} days left',
  'searchFood': 'Search food...',
  'filterAll': 'All',
  'filterExpiring': 'Expiring soon',
  'filterExpired': 'Expired',
  'clearExpired': 'Remove {count} expired items',
  'statTotal': 'Total',
  'statExpiring': 'Expiring',
  'statExpired': 'Expired',
  'itemLimitReached': 'Limit of {max} items reached — unlock unlimited in Shop',
  'cat_meat': 'Meat',
  'cat_vegetable': 'Vegetables',
  'cat_fruit': 'Fruit',
  'cat_dairy': 'Dairy & eggs',
  'cat_drink': 'Drinks',
  'cat_grain': 'Grains',
  'cat_frozen': 'Frozen',
  'cat_snack': 'Snacks',
  'cat_other': 'Other',
  'shoppingListTitle': 'Shopping list',
  'shoppingHint': 'Add item to buy...',
  'shoppingEmpty': 'List is empty. Add items to buy!',
  'toBuy': 'To buy',
  'bought': 'Bought',
  'clearChecked': 'Clear bought',
  'add': 'Add',
  'shareListBranded': 'Made with PantryPal — Get it on Google Play!',
  'adPlaceholder': 'Ad — Remove ads in Shop',
  'save': 'Save',
  'cancel': 'Cancel',
  'shopTitle': 'Shop',
  'shopSubtitle': 'Earn or buy stars to unlock rewards',
  'shopMenuAll': 'All',
  'shopMenuPremium': 'Premium',
  'shopMenuThemes': 'Themes',
  'shopMenuCards': 'Backgrounds',
  'shopMenuSkins': 'Card skins',
  'shopMenuFeatures': 'Features',
  'shopEmptyCategory': 'No items in this category',
  'shopBrowse': 'Browse rewards',
  'yourWallet': 'Your star wallet',
  'coinsLabel': 'stars',
  'earnCoins': 'Earn free stars',
  'earnStepDaily': '• Daily login: +10 stars',
  'earnStepAddFood': 'Add food',
  'earnStepAddFoodDesc': '• Each add: +3 stars (max 10/day)',
  'earnStepShopping': 'Complete shopping',
  'earnStepShoppingDesc': '• Check off item: +2 stars (max 8/day)',
  'earnStepShare': 'Share list',
  'earnStepShareDesc': '• Share: +5 stars (max 3/day)',
  'earnStepBuy': '• Buy star packs via Google Play',
  'claimDailyButton': 'Claim +10 today',
  'dailyRewardDone': 'Already claimed today',
  'buyCoins': 'Buy stars',
  'buyCoinsDesc': 'Purchase star packs to unlock faster.',
  'yourCoins': 'You have {count} stars',
  'coinPack': 'Pack {num}',
  'coinAmount': '{count} stars',
  'earnCoinsHint': 'Or earn free stars from missions above.',
  'billingDisabled': 'Google Billing off — stars only',
  'billingUnavailable': 'Google Play Billing unavailable',
  'productsNotFound': 'Products not found. Check Play Console.',
  'processingPurchase': 'Processing purchase...',
  'openingBilling': 'Opening Google Play...',
  'configNetworkError': 'Network error. Using cached config.',
  'configTimeout': 'Request timed out. Using cached config.',
  'purchaseSuccess': 'Purchase successful!',
  'purchaseFailed': 'Purchase failed',
  'insufficientCoins': 'Not enough stars',
  'alreadyOwned': 'Already owned',
  'owned': 'Owned',
  'active': 'Active',
  'apply': 'Apply',
  'applied': 'Applied!',
  'resetDefault': 'Default',
  'resetToDefault': 'Reset to default',
  'shopRemoveAds': 'Remove ads',
  'shopRemoveAdsDesc': 'Hide ad banners permanently.',
  'removeAdsIap': 'Buy via Google Play',
  'removeAdsUnlocked': 'Ads removed!',
  'buyWithGooglePlay': 'Buy now',
  'coinsAdded': '+{amount} stars added!',
  'coinRewardSub': 'Balance: {balance} stars',
  'notificationExpiry3Days': '{name} expires in 3 days',
  'notificationExpiry7Days': '{name} expires in 7 days',
  'premiumFeatures': 'Premium features',
  'exportData': 'Export data',
  'exportDataDesc': 'Share pantry & shopping list as text',
  'exportEmpty': 'Nothing to export yet',
  'exportDone': 'Export shared',
  'customCategoryColors': 'Category colors',
  'customCategoryColorsDesc': 'Customize color for each food category',
  'pickColor': 'Pick a color',
  'advancedAlertsActive': 'Advanced alerts enabled',
  'advancedAlertsActiveDesc': 'Reminders at 7 days, 3 days, and on expiry day',
  'bulkAddTitle': 'Bulk add food',
  'bulkAddHint': 'Enter one item per line. Optionally add category and days until expiry.',
  'bulkAddFormat': 'Format: Name | Name,category | Name,category,days',
  'bulkAddDefaultDays': 'Default expiry:',
  'bulkAddPlaceholder': 'Milk,dairy,5\nChicken,meat,3\nApples,fruit',
  'bulkAddButton': 'Add all items',
  'bulkAddSuccess': 'Added {count} items',
  'daysUnit': 'days',
  'dailyRewardClaimed': 'Daily reward claimed!',
  'addFoodRewardEarned': '+3 stars — food added',
  'shoppingRewardEarned': '+2 stars — item checked',
  'shareRewardEarned': '+5 stars — list shared',
  'cleanupRewardEarned': '+4 stars — pantry cleaned',
  'themeDefault': 'Default theme',
  'bgDefault': 'Default background',
  'skinDefault': 'Default skin',
  'shopThemeSunset': 'Sunset theme',
  'shopThemeSunsetDesc': 'Warm orange tones.',
  'shopThemeMidnight': 'Midnight theme',
  'shopThemeMidnightDesc': 'Deep blue night.',
  'shopThemeTropical': 'Tropical theme',
  'shopThemeTropicalDesc': 'Fresh green vibes.',
  'shopThemeSakura': 'Sakura theme',
  'shopThemeSakuraDesc': 'Soft cherry blossom pink.',
  'shopBgSunrise': 'Sunrise',
  'shopBgSunriseDesc': 'Warm orange gradient.',
  'shopBgOcean': 'Ocean',
  'shopBgOceanDesc': 'Cool blue waves.',
  'shopBgAurora': 'Aurora',
  'shopBgAuroraDesc': 'Multi-color gradient.',
  'shopBgGalaxy': 'Galaxy',
  'shopBgGalaxyDesc': 'Purple cosmic glow.',
  'shopSkinNeon': 'Neon skin',
  'shopSkinNeonDesc': 'Glowing borders on food cards.',
  'shopSkinClassic': 'Classic skin',
  'shopSkinClassicDesc': 'Warm traditional style.',
  'shopSkinGlass': 'Glass skin',
  'shopSkinGlassDesc': 'Frosted glass effect.',
  'shopFeatUnlimitedItems': 'Unlimited items',
  'shopFeatUnlimitedItemsDesc': 'Add unlimited food items.',
  'shopFeatAdvancedAlerts': 'Advanced alerts',
  'shopFeatAdvancedAlertsDesc': 'Earlier expiry reminders.',
  'shopFeatExport': 'Export data',
  'shopFeatExportDesc': 'Export pantry list.',
  'shopFeatCustomCategories': 'Category colors',
  'shopFeatCustomCategoriesDesc': 'Customize category colors.',
  'shopFeatBulkAdd': 'Bulk add',
  'shopFeatBulkAddDesc': 'Add multiple items at once.',
  'shopFeatNoWatermark': 'No watermark',
  'shopFeatNoWatermarkDesc': 'Share without app branding.',
  'settingsTitle': 'Settings',
  'activeCustomization': 'Active customization',
  'activeTheme': 'Theme',
  'activeBackground': 'Background',
  'activeSkin': 'Card skin',
  'appearance': 'Appearance',
  'darkMode': 'Dark mode',
  'other': 'Other',
  'language': 'Language',
  'vietnamese': 'Tiếng Việt',
  'english': 'English',
  'resetData': 'Clean data',
  'resetDataDesc': 'Remove expired items from pantry',
  'resetDataConfirm': 'Remove all expired food items?',
  'openShop': 'Open Shop',
  'openShopDesc': 'Buy themes, skins and features',
  'privacyPolicy': 'Privacy policy',
  'copyright': '© 2026 PantryPal',
  'privacyTitle': 'Privacy Policy',
  'privacyPolicyTitle': 'PantryPal Privacy Policy',
  'privacyPolicyBody': 'PantryPal stores your food and shopping list data locally on your device. We do not collect sensitive personal data. In-app purchases are processed by Google Play. Contact: support@pantrypal.app',
  'notificationExpiryBody': '{name} expires soon!',
  'notificationChannelName': 'Expiry alerts',
  'notificationChannelDesc': 'Reminders before food expires',
};
