const Map<String, String> appStringsVi = {
  'appName': 'PantryPal',
  'appTagline': 'Quản lý thực phẩm trong nhà thông minh',
  'splashLoading': 'Đang tải tủ thực phẩm...',
  'onboardingTitle1': 'Quản lý tủ đồ',
  'onboardingDesc1': 'Thêm thực phẩm, phân loại theo thịt, rau, đồ uống... và theo dõi mọi thứ trong nhà.',
  'onboardingTitle2': 'Nhắc hết hạn',
  'onboardingDesc2': 'Ghi ngày hết hạn và nhận thông báo trước khi thực phẩm hỏng.',
  'onboardingTitle3': 'Kiếm sao & tùy chỉnh',
  'onboardingDesc3': 'Cày sao miễn phí hoặc mua gói qua Google Play để mở khóa theme, skin thẻ và tính năng premium.',
  'getStarted': 'Bắt đầu',
  'skip': 'Bỏ qua',
  'next': 'Tiếp',
  'navPantry': 'Tủ đồ',
  'navShopping': 'Mua sắm',
  'navShop': 'Cửa hàng',
  'navSettings': 'Cài đặt',
  'pantryTitle': 'Tủ thực phẩm',
  'pantrySubtitle': 'Theo dõi hạn sử dụng mọi thực phẩm',
  'pantryEmpty': 'Chưa có thực phẩm nào. Nhấn + để thêm!',
  'addFood': 'Thêm thực phẩm',
  'editFood': 'Sửa thực phẩm',
  'foodName': 'Tên thực phẩm',
  'category': 'Phân loại',
  'quantity': 'Số lượng',
  'unit': 'Đơn vị (g, ml, hộp...)',
  'hasExpiry': 'Có ngày hết hạn',
  'expiryDate': 'Ngày hết hạn',
  'notes': 'Ghi chú',
  'noExpiry': 'Không HSD',
  'expiredLabel': 'Đã hết hạn',
  'expiresToday': 'Hết hạn hôm nay',
  'daysLeft': 'Còn {days} ngày',
  'searchFood': 'Tìm thực phẩm...',
  'filterAll': 'Tất cả',
  'filterExpiring': 'Sắp hết hạn',
  'filterExpired': 'Đã hết hạn',
  'clearExpired': 'Xóa {count} món hết hạn',
  'statTotal': 'Tổng',
  'statExpiring': 'Sắp hết',
  'statExpired': 'Hết hạn',
  'itemLimitReached': 'Đã đạt giới hạn {max} món — mở khóa không giới hạn trong Cửa hàng',
  'cat_meat': 'Thịt',
  'cat_vegetable': 'Rau',
  'cat_fruit': 'Trái cây',
  'cat_dairy': 'Sữa & trứng',
  'cat_drink': 'Đồ uống',
  'cat_grain': 'Ngũ cốc',
  'cat_frozen': 'Đông lạnh',
  'cat_snack': 'Snack',
  'cat_other': 'Khác',
  'shoppingListTitle': 'Danh sách mua',
  'shoppingHint': 'Thêm món cần mua...',
  'shoppingEmpty': 'Danh sách trống. Thêm món cần mua!',
  'toBuy': 'Cần mua',
  'bought': 'Đã mua',
  'clearChecked': 'Xóa đã mua',
  'add': 'Thêm',
  'shareListBranded': 'Tạo bởi PantryPal — Tải trên Google Play!',
  'adPlaceholder': 'Quảng cáo — Gỡ quảng cáo trong Cửa hàng',
  'save': 'Lưu',
  'cancel': 'Hủy',
  'shopTitle': 'Cửa hàng',
  'shopSubtitle': 'Kiếm sao hoặc mua thêm để mở khóa',
  'shopMenuAll': 'Tất cả',
  'shopMenuPremium': 'Premium',
  'shopMenuThemes': 'Theme',
  'shopMenuCards': 'Hình nền',
  'shopMenuSkins': 'Skin thẻ',
  'shopMenuFeatures': 'Tính năng',
  'shopEmptyCategory': 'Không có mục trong danh mục này',
  'shopBrowse': 'Duyệt phần thưởng',
  'yourWallet': 'Ví sao của bạn',
  'coinsLabel': 'sao',
  'earnCoins': 'Kiếm sao miễn phí',
  'earnStepDaily': '• Đăng nhập hàng ngày: +10 sao',
  'earnStepAddFood': 'Thêm thực phẩm',
  'earnStepAddFoodDesc': '• Thêm mới: +3 sao (tối đa 10/ngày)',
  'earnStepShopping': 'Mua xong món',
  'earnStepShoppingDesc': '• Tick món đã mua: +2 sao (tối đa 8/ngày)',
  'earnStepShare': 'Chia sẻ danh sách',
  'earnStepShareDesc': '• Chia sẻ: +5 sao (tối đa 3/ngày)',
  'earnStepBuy': '• Mua gói sao qua Google Play',
  'claimDailyButton': 'Nhận +10 hôm nay',
  'dailyRewardDone': 'Đã nhận thưởng hôm nay',
  'buyCoins': 'Mua sao',
  'buyCoinsDesc': 'Mua gói sao để mở khóa nhanh hơn.',
  'yourCoins': 'Bạn có {count} sao',
  'coinPack': 'Gói {num}',
  'coinAmount': '{count} sao',
  'earnCoinsHint': 'Hoặc kiếm sao miễn phí ở phần ví phía trên.',
  'billingDisabled': 'Google Billing tắt — chỉ đổi bằng sao',
  'billingUnavailable': 'Google Play Billing không khả dụng',
  'productsNotFound': 'Không tìm thấy sản phẩm. Kiểm tra Play Console.',
  'processingPurchase': 'Đang xử lý giao dịch...',
  'openingBilling': 'Đang mở Google Play...',
  'configNetworkError': 'Lỗi mạng. Dùng cấu hình đã lưu.',
  'configTimeout': 'Hết thời gian chờ. Dùng cấu hình đã lưu.',
  'purchaseSuccess': 'Mua thành công!',
  'purchaseFailed': 'Mua thất bại',
  'insufficientCoins': 'Không đủ sao',
  'alreadyOwned': 'Đã sở hữu',
  'owned': 'Đã mua',
  'active': 'Đang dùng',
  'apply': 'Áp dụng',
  'applied': 'Đã áp dụng!',
  'resetDefault': 'Mặc định',
  'resetToDefault': 'Đã về mặc định',
  'shopRemoveAds': 'Gỡ quảng cáo',
  'shopRemoveAdsDesc': 'Ẩn banner quảng cáo vĩnh viễn.',
  'removeAdsIap': 'Mua qua Google Play',
  'removeAdsUnlocked': 'Đã gỡ quảng cáo!',
  'buyWithGooglePlay': 'Mua ngay',
  'coinsAdded': '+{amount} sao đã thêm!',
  'coinRewardSub': 'Số dư: {balance} sao',
  'notificationExpiry3Days': '{name} hết hạn sau 3 ngày',
  'notificationExpiry7Days': '{name} hết hạn sau 7 ngày',
  'premiumFeatures': 'Tính năng premium',
  'exportData': 'Xuất dữ liệu',
  'exportDataDesc': 'Chia sẻ tủ đồ & danh sách mua dạng text',
  'exportEmpty': 'Chưa có dữ liệu để xuất',
  'exportDone': 'Đã chia sẻ xuất dữ liệu',
  'customCategoryColors': 'Màu phân loại',
  'customCategoryColorsDesc': 'Tùy màu cho từng loại thực phẩm',
  'pickColor': 'Chọn màu',
  'advancedAlertsActive': 'Thông báo nâng cao đang bật',
  'advancedAlertsActiveDesc': 'Nhắc trước 7 ngày, 3 ngày và ngày hết hạn',
  'bulkAddTitle': 'Thêm hàng loạt',
  'bulkAddHint': 'Mỗi dòng một món. Có thể thêm loại và số ngày hết hạn.',
  'bulkAddFormat': 'Định dạng: Tên | Tên,loại | Tên,loại,số_ngày',
  'bulkAddDefaultDays': 'HSD mặc định:',
  'bulkAddPlaceholder': 'Sữa,dairy,5\nThịt gà,meat,3\nTáo,fruit',
  'bulkAddButton': 'Thêm tất cả',
  'bulkAddSuccess': 'Đã thêm {count} món',
  'daysUnit': 'ngày',
  'dailyRewardClaimed': 'Đã nhận thưởng hàng ngày!',
  'addFoodRewardEarned': '+3 sao — thêm thực phẩm',
  'shoppingRewardEarned': '+2 sao — mua xong món',
  'shareRewardEarned': '+5 sao — chia sẻ danh sách',
  'cleanupRewardEarned': '+4 sao — dọn tủ đồ',
  'themeDefault': 'Theme mặc định',
  'bgDefault': 'Nền mặc định',
  'skinDefault': 'Skin mặc định',
  'shopThemeSunset': 'Theme hoàng hôn',
  'shopThemeSunsetDesc': 'Tông cam ấm áp.',
  'shopThemeMidnight': 'Theme đêm',
  'shopThemeMidnightDesc': 'Xanh đêm sâu lắng.',
  'shopThemeTropical': 'Theme nhiệt đới',
  'shopThemeTropicalDesc': 'Xanh tươi mát.',
  'shopThemeSakura': 'Theme sakura',
  'shopThemeSakuraDesc': 'Hồng hoa anh đào.',
  'shopBgSunrise': 'Bình minh',
  'shopBgSunriseDesc': 'Nền gradient cam ấm.',
  'shopBgOcean': 'Đại dương',
  'shopBgOceanDesc': 'Xanh biển trong.',
  'shopBgAurora': 'Cực quang',
  'shopBgAuroraDesc': 'Gradient nhiều màu.',
  'shopBgGalaxy': 'Galaxy',
  'shopBgGalaxyDesc': 'Tím xanh huyền ảo.',
  'shopSkinNeon': 'Skin Neon',
  'shopSkinNeonDesc': 'Viền phát sáng cho thẻ thực phẩm.',
  'shopSkinClassic': 'Skin Classic',
  'shopSkinClassicDesc': 'Phong cách ấm áp.',
  'shopSkinGlass': 'Skin Glass',
  'shopSkinGlassDesc': 'Hiệu ứng kính mờ.',
  'shopFeatUnlimitedItems': 'Không giới hạn món',
  'shopFeatUnlimitedItemsDesc': 'Thêm không giới hạn thực phẩm.',
  'shopFeatAdvancedAlerts': 'Thông báo nâng cao',
  'shopFeatAdvancedAlertsDesc': 'Nhắc sớm hơn trước hết hạn.',
  'shopFeatExport': 'Xuất dữ liệu',
  'shopFeatExportDesc': 'Xuất danh sách tủ đồ.',
  'shopFeatCustomCategories': 'Màu phân loại',
  'shopFeatCustomCategoriesDesc': 'Tùy chỉnh màu danh mục.',
  'shopFeatBulkAdd': 'Thêm hàng loạt',
  'shopFeatBulkAddDesc': 'Thêm nhiều món cùng lúc.',
  'shopFeatNoWatermark': 'Không watermark',
  'shopFeatNoWatermarkDesc': 'Chia sẻ không logo app.',
  'settingsTitle': 'Cài đặt',
  'activeCustomization': 'Đang áp dụng',
  'activeTheme': 'Theme',
  'activeBackground': 'Hình nền',
  'activeSkin': 'Skin thẻ',
  'appearance': 'Giao diện',
  'darkMode': 'Chế độ tối',
  'other': 'Khác',
  'language': 'Ngôn ngữ',
  'vietnamese': 'Tiếng Việt',
  'english': 'English',
  'resetData': 'Dọn dữ liệu',
  'resetDataDesc': 'Xóa món hết hạn khỏi tủ',
  'resetDataConfirm': 'Xóa tất cả thực phẩm đã hết hạn?',
  'openShop': 'Mở Cửa hàng',
  'openShopDesc': 'Mua theme, skin và tính năng',
  'privacyPolicy': 'Chính sách bảo mật',
  'copyright': '© 2026 PantryPal',
  'privacyTitle': 'Chính sách bảo mật',
  'privacyPolicyTitle': 'Chính sách bảo mật PantryPal',
  'privacyPolicyBody': 'PantryPal lưu dữ liệu thực phẩm và danh sách mua cục bộ trên thiết bị của bạn. Chúng tôi không thu thập dữ liệu cá nhân nhạy cảm. Mua hàng in-app được xử lý bởi Google Play. Liên hệ: support@pantrypal.app',
  'notificationExpiryBody': '{name} sắp hết hạn!',
  'notificationChannelName': 'Hạn sử dụng',
  'notificationChannelDesc': 'Thông báo thực phẩm sắp hết hạn',
};
